# Only build on master branch and stable branch
if: branch = master OR branch = stable
matrix:
  include:
    # Build JAR
    - language: java
      jdk: oraclejdk8
      # Cache the build files
      cache:
        directories:
        - .autoconf
        - $HOME/.m2
        - $HOME/.gradle
      # Deploy to GH releases
      deploy:
        provider: script
        script: ./github_release_script.sh
        skip_cleanup: true
        on:
          repo: whsmc/GUIShopMinus
          branch: master

    # Build config gen
    - language: node_js
      node_js:
        - "10"
      # Cache dependencies
      cache: npm
      # Build and install deps
      script:
        - cd website
        - npm ci
        - npm run build
      deploy:
        # Deploy the webapp to gh-pages
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: website/dist
        on:
          branch: master
