/*!
 * Copyright (C) 2019  Zachary Kohnen
 */

import JSON5 from "json5";
import "normalize.css";
import Vue from "vue";
import items from "./items.json";
import mccodes from "./mccodes.json";
import "./styles.scss";
import { fuzzySearch, getItemIcon, getItemInfo, IMapObject, parseColorCodesToHTML, zipObject } from "./util";

interface IStore {
    name: string;
    submenus: ISubmenu[];
}

interface ISubmenu {
    icon: IMaterial;
    name: string;
    description: string;
    items: IItem[];
}

interface IItem {
    material: IMaterial;
    name: string;
    amount: number;
    price: number;
    sellprice: number;
}

export interface IMaterial {
    type: number;
    meta: number;
}

export interface IMaterialInfo {
    type: number;
    meta: number;
    name: string;
    text_type: string;
}

(async () => {
    const colorsZipped = zipObject(mccodes.colors).map(x => ({
        code: x.key,
        ...x.value
    }));

    const stylesZipped = zipObject(mccodes.styles).map(x => ({
        code: x.key,
        ...x.value
    }));

    let store: IStore = {
        name: "&2Example &3Shop &4Name",
        submenus: [
            {
                description: "&8This is an example description",
                icon: {
                    meta: 0,
                    type: 40
                },
                items: [
                    {
                        amount: 10,
                        material: {
                            meta: 0,
                            type: 10
                        },
                        name: "&cCool Exclusive Item",
                        price: 1000,
                        sellprice: 1
                    }
                ],
                name: "&5Example Submenu"
            }
        ]
    };

    let vm = new Vue({
        data: {
            colors: colorsZipped,
            items: await Promise.all(items.map(async x => getItemIcon(x as IMaterial))),
            store,
            styles: stylesZipped
        },
        el: "#app",
        methods: {
            getItemIcon,
            getItemInfo,
            parseColorCodesToHTML,
            upload() {
                let input = document.querySelector<HTMLInputElement>("#fileupload");

                if (input !== null) {
                    input.click();
                }
            },
            uploadfile(event: Event) {
                let input = document.querySelector<HTMLInputElement>("#fileupload");

                if (input !== null) {
                    let files = input.files;

                    if (files !== null) {
                        let fr = new FileReader();
                        fr.onload = () => {
                            console.log(fr.result);

                            try {
                                let parsed = JSON5.parse(fr.result as string);

                                // SANITIZE

                                this.store = parsed as IStore;
                            } catch (e) {
                                alert(e);
                            }
                        };
                        fr.readAsText(files[0]);
                    }
                }
            },
            download() {
                const header = `/*\n\n* DO NOT EDIT THIS FILE\n*\n* This file was generated at ${new Date().toISOString()}\n*/\n\n`;

                let element = document.createElement("a");
                element.setAttribute("href", `data:application/json;charset=utf-8,${encodeURIComponent(header)}${encodeURIComponent(JSON.stringify(this.store))}`);
                element.setAttribute("download", "shop.json");

                document.body.appendChild(element);
                element.style.display = "none";
                element.click();
                document.body.removeChild(element);
            }
        }
    });
})().catch(e => console.error(e));
